SELECT 
    UGB.TITLE, 
    UGB.BOARD_ID, 
    UGR.REPLY_ID, 
    UGR.WRITER_ID, 
    UGR.CONTENTS, 
    DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM 
    USED_GOODS_BOARD UGB
JOIN 
    USED_GOODS_REPLY UGR ON UGB.BOARD_ID = UGR.BOARD_ID
WHERE 
    -- 'YYYY-MM-DD' 포맷을 사용하여 2022년 10월에 작성된 게시글을 필터링
    UGB.CREATED_DATE >= '2022-10-01' AND UGB.CREATED_DATE <= '2022-10-31'
ORDER BY 
    UGR.CREATED_DATE ASC, -- 댓글 작성일 기준으로 오름차순 정렬
    UGB.TITLE ASC; -- 게시글 제목 기준으로 오름차순 정렬